services:

  postgres:
    image: postgres:15
    container_name: shop-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: shopdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shopdb"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./Shop.Api
      dockerfile: Dockerfile.dev

    container_name: shop-api

    working_dir: /src

    volumes:
      - ./Shop.Api:/src

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=shopdb;Username=admin;Password=12345

    ports:
      - "5000:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: